// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TUI_SimulatorFlightCosts_AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Calculate_Flight_Distance_And_Fuel_NeededFeature : Xunit.IClassFixture<Calculate_Flight_Distance_And_Fuel_NeededFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Calculate_flight_distance_and_fuel_needed.feature"
#line hidden
        
        public Calculate_Flight_Distance_And_Fuel_NeededFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Calculate_flight_distance_and_fuel_needed", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(Calculate_Flight_Distance_And_Fuel_NeededFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Calculate_flight_distance_and_fuel_needed")]
        [Xunit.TraitAttribute("Description", "Determine distance and fuel consumption between airport London and airport Roissy" +
            " Charles De Gaulles")]
        public virtual void DetermineDistanceAndFuelConsumptionBetweenAirportLondonAndAirportRoissyCharlesDeGaulles()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Determine distance and fuel consumption between airport London and airport Roissy" +
                    " Charles De Gaulles", "");
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("A flight which has a departure airport with GPS Position (London - 51.5048, 0.052" +
                    "745500000014545)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.And("has a destination airport with GPS Position (Roissy Charlles De Gaulle - 49.007, " +
                    "2.559790000000021)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.And("the aircraft fuel consumption per distance/flight time (10000 L/km/h) + takeoff e" +
                    "ffort (10000 L/km/h)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.When("the flight takes place", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("the travel distance was 340 km", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
 testRunner.And("the total fuel consumption was 70000 L", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                Calculate_Flight_Distance_And_Fuel_NeededFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                Calculate_Flight_Distance_And_Fuel_NeededFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion

